"""Create Table

Revision ID: 08cfdf4a0fa9
Revises: 84d7b51c73a4
Create Date: 2025-10-31 13:21:14.558138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08cfdf4a0fa9'
down_revision: Union[str, Sequence[str], None] = '84d7b51c73a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['id'])
    op.add_column('order_items', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_order_items_order_item_id'), table_name='order_items')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_column('order_items', 'order_item_id')
    op.add_column('orders', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'order_id')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('shipping_order_id_fkey'), 'shipping', type_='foreignkey')
    op.create_foreign_key(None, 'shipping', 'orders', ['order_id'], ['id'])
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_column('users', 'id')
    op.drop_constraint(None, 'shipping', type_='foreignkey')
    op.create_foreign_key(op.f('shipping_order_id_fkey'), 'shipping', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['order_id'])
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_order_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'id')
    op.add_column('order_items', sa.Column('order_item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['order_id'])
    op.create_index(op.f('ix_order_items_order_item_id'), 'order_items', ['order_item_id'], unique=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
