"""Create Table

Revision ID: 84d7b51c73a4
Revises: df5ba4bb342f
Create Date: 2025-10-31 12:53:49.427005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d7b51c73a4'
down_revision: Union[str, Sequence[str], None] = 'df5ba4bb342f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=True))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'subtotal')
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('orders_shipping_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_billing_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'billing_address_id')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('billing_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_billing_address_id_fkey'), 'orders', 'addresses', ['billing_address_id'], ['address_id'])
    op.create_foreign_key(op.f('orders_shipping_address_id_fkey'), 'orders', 'addresses', ['shipping_address_id'], ['address_id'])
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('orders', 'created_at')
    op.add_column('order_items', sa.Column('subtotal', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('unit_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
