"""Add order total_amount & status columns

Revision ID: 86a3223af780
Revises: af0cc718372e
Create Date: 2025-11-01 13:26:34.250481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a3223af780'
down_revision: Union[str, Sequence[str], None] = 'af0cc718372e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total_amount')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
