"""orders table fix

Revision ID: 8bc46270e940
Revises: 86a3223af780
Create Date: 2025-11-01 13:34:01.572736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc46270e940'
down_revision: Union[str, Sequence[str], None] = '86a3223af780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('orders', 'order_date')
    op.drop_column('orders', 'order_id')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(op.f('shipping_order_id_fkey'), 'shipping', type_='foreignkey')
    op.create_foreign_key(None, 'shipping', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipping', type_='foreignkey')
    op.create_foreign_key(op.f('shipping_order_id_fkey'), 'shipping', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['order_id'])
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('orders', sa.Column('order_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
