"""Fix foreign keys and add missing columns

Revision ID: a7fc6c50fcd9
Revises: 0a241048f143
Create Date: 2025-10-31 13:32:41.631229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fc6c50fcd9'
down_revision: Union[str, Sequence[str], None] = '0a241048f143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
